const OPTIONS = ["2cc Roche",
                "2cc DIN ISO",
                "2cc Concquer",
                "3cc Roche",
                "3cc DIN ISO",
                "3cc Concquer",
                "6cc Roche",
                "6cc DIN ISO",
                "6cc Concquer",
                "10cc Roche",
                "10cc DIN ISO",
                "10cc Concquer",
                "15cc Roche",
                "15cc DIN ISO",
                "15cc Concquer",
                "20cc Roche",
                "20cc DIN ISO",
                "20cc Concquer",
                "50cc Roche",
                "50cc DIN ISO",
                "50cc Concquer",
];

export default OPTIONS;